### ISSUE TITLE
Flexdashboard Slides

### ISSUE THREAD

**Issue by z-wix** [z-wix/flexdashboard#2]
We need to make some slides for Marc that he can use in class.

I think that I have been making it too complicated myself so you can help me make it simple to understand that students who are just learning about Rmarkdown can understand.

Look over my slides right now `00_flexdashboard_walkthru.Rmd`  (they are incomplete at the moment) and we can schedule a time to look over it together.

**Comment by z-wix** [comment]
@JamesStewart-BYU I have gone through the slides again, I think they look a lot better. I was having an issue with using shiny functions in the slides but I figures out to use eval=FALSE in the r code chunk parameter which doesn't run the code but still displays it. 

It is looking pretty good until after adding the value box. After that I had some code to add a table but might get rid of that. I am not sure how to end it. I don't remember if Marc wants to include publishing to shinyapps.io (the website that you can use to share shiny apps and flex dashboards through links)

So why don't you give it a look and see if things make sense. I can work more on it tonight.

**Comment by JamesStewart5** [comment]
@z-wix Sounds great! I'll try and look at it tonight but I'll for sure go over it tomorrow sometime

**Comment by z-wix** [comment]
Add a section that details how to publish on shinyapps.io
